# Generated by Django 2.2.6 on 2020-10-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airman',
            fields=[
                ('ID_NO', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_no', models.IntegerField()),
                ('Address', models.CharField(max_length=1000, null=True)),
                ('Rank', models.CharField(max_length=5, null=True)),
                ('Trade', models.CharField(max_length=5, null=True)),
                ('Section', models.CharField(max_length=5, null=True)),
                ('Unit', models.CharField(max_length=5, null=True)),
                ('Ip_NO', models.IntegerField()),
                ('User_name', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
