# Generated by Django 2.2.6 on 2020-10-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airman',
            name='Series_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='airman',
            name='Rank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='airman',
            name='Section',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='airman',
            name='Trade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='airman',
            name='Unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
