# Generated by Django 2.2.6 on 2020-10-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defence', '0002_auto_20201016_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='airman',
        ),
    ]
