# Generated by Django 2.2.6 on 2020-10-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uaccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='airman',
            new_name='User',
        ),
    ]
