# Generated by Django 2.2.6 on 2020-10-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uaccount', '0002_auto_20201019_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AUser',
        ),
    ]
