# Generated by Django 2.2.6 on 2020-10-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uaccount', '0003_auto_20201019_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AUser',
            new_name='User',
        ),
    ]
