# Generated by Django 2.2.6 on 2020-10-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uaccount', '0004_auto_20201019_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Airman',
        ),
    ]
