# Generated by Django 2.2.6 on 2020-10-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uaccount', '0006_auto_20201019_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airman',
            new_name='User',
        ),
    ]
