# Generated by Django 2.2.6 on 2020-10-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccount', '0009_auto_20201021_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='password',
            field=models.CharField(default=123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
