# Generated by Django 2.2.6 on 2020-10-22 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uaccount', '0010_auto_20201021_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='password',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
